version: "3.8"

services:
  react-ui:
    build:
      context: ./
    ports:
      - "3000:3000"
    container_name: react-ui
    stdin_open: true
    volumes:
      - ./src:/app/src
      - /app/node_modules
